import React, { useState } from 'react';
import { 
  BookOpen, 
  GraduationCap, 
  HelpCircle, 
  ChevronDown, 
  ChevronUp, 
  Zap, 
  ShieldCheck, 
  Layers, 
  AlertOctagon,
  Sparkles
} from 'lucide-react';

export const BASIC_QUESTIONS = [
  {
    question: "1. What is the fundamental difference between Distance Vector and Link State routing?",
    answer: "In Distance Vector (Bellman-Ford), routers share routing table estimates only with direct neighbors and lack global network topology knowledge ('routing by rumor'). In Link State (Dijkstra/OSPF), every router floods Link State Advertisements (LSAs) to build an identical global Link State Database (LSDB) and independently calculates the shortest path tree from itself."
  },
  {
    question: "2. How does the Bellman-Ford equation work in Distance Vector routing?",
    answer: "For a router x wishing to reach destination y, its shortest distance estimate is: D_x(y) = min_v [ c(x,v) + D_v(y) ], where v ranges over all physical neighbors of x, c(x,v) is the direct link cost to v, and D_v(y) is neighbor v's advertised distance to y."
  },
  {
    question: "3. How does Dijkstra's Algorithm operate in Link State routing?",
    answer: "Dijkstra maintains two sets: Permanent (Settled nodes N') and Tentative (candidate nodes). In each step, the algorithm chooses the tentative node u with the minimum tentative distance, adds u to N', and relaxes all unvisited neighbors v: if dist[u] + cost(u,v) < dist[v], then dist[v] = dist[u] + cost(u,v) and prev[v] = u."
  },
  {
    question: "4. What is the Count-to-Infinity problem, and why does it occur in Distance Vector?",
    answer: "When a link fails or its cost increases significantly, two adjacent routers can fall into a routing loop where they iteratively update their routes based on each other's outdated estimates, slowly counting up to infinity (e.g. 16 in RIP). Solutions include Split Horizon and Poison Reverse."
  },
  {
    question: "5. What is Split Horizon and Poison Reverse?",
    answer: "Split Horizon dictates that a router should never advertise a route back to the neighbor from which it learned that route. Poison Reverse takes this further by advertising that route back to the source neighbor with a distance of infinity (∞), immediately breaking 2-node routing loops."
  },
  {
    question: "6. What is network convergence?",
    answer: "Network convergence is the state where all routers in the network have consistent, complete, and optimal routing tables following topology changes or startup, with no further routing table updates being generated."
  },
  {
    question: "7. Why is Link State generally preferred in large enterprise networks over Distance Vector?",
    answer: "Link State (e.g., OSPF, IS-IS) converges much faster, is completely free of count-to-infinity routing loops, supports hierarchical areas (OSPF Areas), and responds immediately to link failures without iterative neighbor cascading."
  },
  {
    question: "8. What is the message overhead comparison between the two protocols?",
    answer: "Distance Vector exchanges distance vectors periodically or upon change strictly between 1-hop neighbors (low bandwidth per message, but slow multi-hop propagation). Link State floods Link State Packets globally across the entire autonomous system during link state changes (higher initial flooding overhead, but zero periodic vector flooding once stable)."
  },
  {
    question: "9. What is an LSP (Link State Packet) and what does it contain?",
    answer: "An LSP is a packet generated by a router containing: Router ID, Sequence Number, Age, and a list of direct neighbor router IDs along with their operational link costs."
  },
  {
    question: "10. What are real-world protocol examples of Distance Vector and Link State?",
    answer: "Distance Vector: RIPv1, RIPv2, BGP (Path Vector variant), Cisco IGRP/EIGRP (Advanced Distance Vector / DUAL). Link State: OSPF (Open Shortest Path First) and IS-IS (Intermediate System to Intermediate System)."
  }
];

export default function HelpPanel() {
  const [expandedIndex, setExpandedIndex] = useState(0);

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12">
      
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl">
        <div className="flex items-center space-x-2 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-1">
          <BookOpen className="w-4 h-4" />
          <span>Routing Fundamentals</span>
        </div>
        <h2 className="text-2xl font-extrabold text-white tracking-tight">
          Theory
        </h2>
        <p className="text-sm text-slate-400 mt-1 max-w-2xl">
          Core principles, algorithmic formulations, and foundational concepts for Distance Vector and Link State routing protocols.
        </p>
      </div>

      {/* Quick Core Concept Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        
        {/* Distance Vector Core */}
        <div className="bg-[#0f172a] rounded-3xl border border-cyan-500/30 p-6 shadow-xl space-y-3">
          <div className="flex items-center space-x-2 text-cyan-400 font-bold">
            <Zap className="w-5 h-5" />
            <h3 className="text-base">Distance Vector (Bellman-Ford)</h3>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Distance Vector is an <strong>iterative, asynchronous, and distributed</strong> algorithm where routers exchange distance estimates exclusively with their directly connected physical neighbors.
          </p>
          <div className="bg-slate-950 rounded-xl p-3 border border-slate-800 font-mono text-xs text-cyan-300">
            D_x(y) = min_v [ c(x,v) + D_v(y) ]
          </div>
          <div className="text-[11px] text-slate-400 space-y-1">
            <div>• <strong>Convergence:</strong> Continues until no router updates its vector.</div>
            <div>• <strong>Key drawback:</strong> Slow convergence and Count-to-Infinity.</div>
          </div>
        </div>

        {/* Link State Core */}
        <div className="bg-[#0f172a] rounded-3xl border border-purple-500/30 p-6 shadow-xl space-y-3">
          <div className="flex items-center space-x-2 text-purple-400 font-bold">
            <ShieldCheck className="w-5 h-5" />
            <h3 className="text-base">Link State (Dijkstra / OSPF)</h3>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Link State is a <strong>global routing algorithm</strong> where each node broadcasts link state packets (LSPs) across the entire network so every node has a synchronized, identical view of the topology.
          </p>
          <div className="bg-slate-950 rounded-xl p-3 border border-slate-800 font-mono text-xs text-purple-300">
            D(v) = min(D(v), D(u) + c(u,v))
          </div>
          <div className="text-[11px] text-slate-400 space-y-1">
            <div>• <strong>Computation:</strong> Independent local Dijkstra on LSDB.</div>
            <div>• <strong>Key advantage:</strong> Fast loop-free convergence.</div>
          </div>
        </div>

      </div>

      {/* Interactive Basics to Know Accordion */}
      <div className="bg-[#0f172a] rounded-3xl border border-slate-800 p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <HelpCircle className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold text-slate-100 uppercase tracking-wide">
              BASICS TO KNOW
            </h3>
          </div>
          <span className="text-xs text-slate-400">Click to expand</span>
        </div>

        <div className="space-y-2.5">
          {BASIC_QUESTIONS.map((q, idx) => {
            const isExpanded = expandedIndex === idx;

            return (
              <div
                key={idx}
                className="bg-slate-950/70 border border-slate-800/80 rounded-2xl overflow-hidden transition-all"
              >
                <button
                  onClick={() => setExpandedIndex(isExpanded ? null : idx)}
                  className="w-full text-left p-4 flex items-center justify-between space-x-3 hover:bg-slate-900/50 transition-colors"
                >
                  <span className="text-xs sm:text-sm font-semibold text-slate-200">
                    {q.question}
                  </span>
                  {isExpanded ? (
                    <ChevronUp className="w-4 h-4 text-emerald-400 shrink-0" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                  )}
                </button>

                {isExpanded && (
                  <div className="px-4 pb-4 pt-1 text-xs text-slate-300 leading-relaxed border-t border-slate-800/50 bg-slate-900/30">
                    <p className="text-emerald-300/90 font-sans">
                      {q.answer}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
}
